from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Mapping


REQUIRED_FIELDS = (
    "state_revision",
    "project_name",
    "active_research_line",
    "current_task",
    "scientific_gate",
    "next_action",
    "updated_at",
)


def _mapping(value: object, field: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise ValueError(f"{field} must be an object")
    return value


def render_status(state: Mapping[str, Any]) -> str:
    for field in REQUIRED_FIELDS:
        if field not in state:
            raise ValueError(f"missing required field: {field}")
    gate = _mapping(state["scientific_gate"], "scientific_gate")
    next_action = _mapping(state["next_action"], "next_action")
    evidence = state.get("status_evidence", [])
    if not isinstance(evidence, list) or not all(isinstance(item, str) for item in evidence):
        raise ValueError("status_evidence must be a list of paths")
    evidence_lines = "\n".join(f"- `{item}`" for item in evidence) or "- 尚未登记"
    blocker = state.get("blocked_reason") or "无"
    return (
        "<!-- AUTO-GENERATED by tools/project/render_status.py; DO NOT EDIT. -->\n"
        "# 项目状态\n\n"
        f"- 项目：{state['project_name']}\n"
        f"- 当前研究线：{state['active_research_line']}\n"
        f"- 当前任务：`{state['current_task']}`\n"
        f"- 科学门槛：{gate.get('stage', 'N/A')} — **{gate.get('decision', 'N/A')}**\n"
        f"- 阻塞原因：{blocker}\n"
        f"- 唯一下一步：{next_action.get('command', next_action.get('action_type', 'N/A'))}\n"
        f"- 状态修订：{state['state_revision']}\n"
        f"- 更新时间：{state['updated_at']}\n\n"
        "## 证据\n\n"
        f"{evidence_lines}\n"
    )


def render_to_path(state_path: Path, output_path: Path, *, check: bool) -> None:
    state = json.loads(state_path.read_text(encoding="utf-8"))
    expected = render_status(state)
    if check:
        actual = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        if actual != expected:
            raise RuntimeError(f"{output_path} is out of date")
        return
    output_path.write_text(expected, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--state", type=Path, default=Path(".research/execution_state.json"))
    parser.add_argument("--output", type=Path, default=Path("STATUS.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    render_to_path(args.state, args.output, check=args.check)


if __name__ == "__main__":
    main()
